[project]
name = "tp_debruijn"
version = "0.1.0"
description = "Assembleur basÃ© sur un graphe de De Bruijn"
requires-python = ">=3.10"

dependencies = [
    "networkx",
    "matplotlib",
    "scipy",
]

[tool.uv]
dev-dependencies = []
